Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
